### ISSUE TITLE
[1.10.2] Crucible (possibly other blocks) Oredic support.

### ISSUE THREAD

**Issue by Claycorp** [BeetoGuy/BetterWithMods#317] opened 2017-05-09 00:55 UTC
I made a stoked Crucible recipe and used an oredic entry in it. The result is the oredic entry is ignored. Can we get support for that or is that not possible?

**Comment by BeetoGuy** [comment] 2017-05-09 02:18
Can you post the script? I could have sworn they supported the ore dictionary.

**Comment by Claycorp** [comment] 2017-05-09 02:27
```mods.betterwithmods.StokedCrucible.add(<immersiveengineering:stoneDecoration>, slag, [<ceramics:unfired_clay:4> * 8, <minecraft:clay_ball> * 16, <ore:sand> * 16, <charcoal_pit:stone_creosote_collector>]);```
Resulting recipe: http://i.imgur.com/lFWwvxa.png You can see it even skips the slot where the oredic entry is.

**Comment by KnightMiner** [comment] 2017-05-09 04:10
Also seems to be using the wrong metadata on the ceramics item, the one you provided should give porcelain, not unfired buckets.

Since it seems important, is this 1.11.2 or 1.10.2? Exact BWM and CraftTweaker versions would probably be more helpful.

**Comment by Claycorp** [comment] 2017-05-09 04:14
Metadata was my problem, you can ignore that. Deving in two work spaces gets confusing sometimes >.>
I'll include the other info quick also.
MC: 1.10.2
Forge: 12.18.3.2281
CraftTweaker: 3.0.24
BWM: 0.14.22

**Comment by BeetoGuy** [comment] 2017-05-09 05:55
Oh, okay, I know what the problem is. MineTweaker doesn't expect stack sizes for Ore Dictionary entries for some reason. The main workaround we have is condensing identical OreDict entries into a condensed stack when reading the script. Makes the script a bit more of a pain, but I couldn't find any other alternative.

**Comment by Claycorp** [comment] 2017-05-09 16:23
Well... That's good to know. This might affect other recipes I have done also. Perhaps I should see if that can get fixed in CraftTweaker or not? Thanks for the info!

**Comment by BeetoGuy** [comment] 2017-05-09 17:38
Probably wouldn't hurt. I've tried making the tweaks myself, but ended up hitting a wall with it.

**Comment by primetoxinz** [comment] 2017-05-17 01:09
Closing. Hopefully this gets fixed in Crafttweaker.

**Closed by primetoxinz** 2017-05-17 01:09 UTC

**Comment by Claycorp** [comment] 2017-05-28 19:42
Update:
The original problem was fixed but now the recipe lists every item separate. Not sure if this is an issue on your side or MTLib.
https://pastebin.com/vnnFvhau
