### ISSUE TITLE
CraftTweaker & JEI & You!

### ISSUE THREAD

**Issue by bookerthegeek** [BeetoGuy/BetterWithMods#336] opened 2017-05-14 08:59 UTC
## Heyo ##
Hello again! Small issue with your JEI and CraftTweaker integration. After removing a recipe, then adding it back in, it does not show up in JEI. Still works, just does not show up. Interestingly Enough, it does show up in the Kiln recipe list...
### Proof ###
![No Recipe](https://i.imgur.com/0cDRyJY.png)
![WhatTheHell](https://i.imgur.com/Hdh5ZZU.png)
### Script ###
```
mods.betterwithmods.Saw.remove(<betterwithmods:debarked_old>);
mods.betterwithmods.Saw.add([<betterwithmods:wood_siding> * 2], <betterwithmods:debarked_old>);
```

### Versions ###
- MTLib-2.0.1
- CraftTweaker-1.11.2-3.0.24
- Forge-1.11.2-13.20.0.2296-universal
- JEI_1.11.2-4.3.5.275

I have tried both:
- Better With Mods-1.2.4-1.11.2 
- Better With Mods-1.2.6-1.11.2 

#### Request ####
Could you support wildcards for metadata? So that the following script works? If not that is fine. :)
```
mods.betterwithmods.Saw.remove(<betterwithmods:debarked_old:*>);
```

**Comment by DaedalusGame** [comment] 2017-05-14 13:58
you can try setting the meta to 32767 (this is the value of OreDictionary.WILDCARD_VALUE) for now

**Comment by KnightMiner** [comment] 2017-05-14 14:28
I did notice a few of the recipes seemed to end up in the wrong place. I think it was a mill recipe I added that ended up in the crucible, meanwhile my crucible recipes showed in the right place.

**Comment by primetoxinz** [comment] 2017-05-14 14:33
I honestly don't know how to fix this, it didn't become an issue until I moved to the latest JEI version and implemented the new `IModRegistry::handleRecipes`. It would make sense that this happens because the Kiln and Saw use the same base recipe class and so do Cauldron, Mill and Crucible. So it seems likely that they would cross due to [this](https://github.com/BeetoGuy/BetterWithMods/blob/1.11/src/main/java/betterwithmods/integration/jei/JEI.java#L48-L54) somehow.  Maybe @mezz can help.

**Comment by bookerthegeek** [comment] 2017-05-14 17:18
- jei_1.11.2-4.3.3.270

**Comment by primetoxinz** [comment] 2017-05-14 17:20
might not be the problem but try 4.3.5.275

**Comment by bookerthegeek** [comment] 2017-05-14 17:30
Tried with JEI-1.11.2-4.3.5.275, same issue. Updated post with information.

**Comment by mezz** [comment] 2017-05-14 17:55
I think the fix for this is a part of the JEI API that is still evolving.
Along with the new `IModRegistry::handleRecipes`, there are new methods for adding and removing recipes are runtime which take a categoryUID to make sure that they are applied to the right category.
I am pretty sure CraftTweaker hasn't had enough time to start using those methods, so this bug where things end up in the wrong category is still around.

**Comment by primetoxinz** [comment] 2017-05-14 17:56
So, not something that can be fixed no my side?

**Comment by mezz** [comment] 2017-05-14 17:57
I assume you have one recipe class that is used for several categories. You may be able to fix this on your side by splitting your recipes into separate classes for each category.
I'm not sure how your CraftTweaker integration works though. Do you have a link to the code I can look at?

**Comment by primetoxinz** [comment] 2017-05-14 18:00
A majority of recipe code is handled through [BulkRecipe](https://github.com/BeetoGuy/BetterWithMods/blob/1.11/src/main/java/betterwithmods/common/registry/bulk/BulkRecipe.java), and 
[this](https://github.com/BeetoGuy/BetterWithMods/tree/1.11/src/main/java/betterwithmods/integration/minetweaker) is all the CraftTweaker code, and most of it just extends BulkAdd/Remove or BMAdd/Remove.

**Comment by mezz** [comment] 2017-05-14 18:06
Ok I think the fix has to be in CraftTweaker, they need to use the new API and request the recipe category in their API when you add or remove recipes.

The issue is you have a `BulkRecipe` and CraftTweaker gives it to JEI with `addRecipe(Object)`. JEI tries to figure out who handles it. It doesn't know which category the recipe belongs to, so it goes through the categories asking if they can handle the recipe. All your categories handle `BulkRecipe` so the first one that says it can handle it gets it. 
The new API is `addRecipe(IRecipeWrapper, String recipeCategoryUid)` which takes out the guesswork and makes sure the recipe goes to the right place, but it means some reworking of CraftTweaker to properly keep track of categories, which is something it never had to worry about before.

**Comment by mezz** [comment] 2017-05-14 18:08
For a workaround, you can extend `BulkRecipe` for each type of recipe you have, so they are different classes (`RecipeKiln extends BulkRecipe`, `RecipeSaw extends BulkRecipe`, etc). Then when you add it to JEI, it is clear which category it belongs to.

**Comment by primetoxinz** [comment] 2017-05-14 18:08
Probably what I'll end up doing

**Comment by primetoxinz** [comment] 2017-05-17 00:19
Temporary fix implemented, closing for now. If the fix doesn't work, just say so here.

**Closed by primetoxinz** 2017-05-17 00:19 UTC
