### ISSUE TITLE
Gearboxes still break from storms in the Desert

### ISSUE THREAD

**Issue by WesCook** [BeetoGuy/BetterWithMods#199] opened 2016-12-18 11:54 UTC
Despite deserts having no weather, gearboxes are still broken by storms.  It took me some time to figure out why my gearboxes continued to break.

**Comment by BeetoGuy** [comment] 2016-12-18 18:31
That's pretty much intended behavior, since the idea is that while it doesn't rain, there would technically be windstorms, or in the case of Dynamic Surroundings, sandstorms.

**Comment by Koward** [comment] 2016-12-18 18:56
But there's no visual indication of storms in the mod so that's completely invisible to the user. It would be great indeed for a compatibility feature with weather mods, of course, but without it it will feel like a bug.

**Comment by BeetoGuy** [comment] 2016-12-18 19:02
Yeah, that's true. Maybe a config option to make windmills overpower in deserts?

**Comment by primetoxinz** [comment] 2016-12-18 20:13
could add a visual sandstorm effect to make it seem more immersive

**Comment by BeetoGuy** [comment] 2016-12-18 21:00
Yeah, it wouldn't have to be anything too intrusive, maybe some sand particles kicking up in dry biomes.

**Comment by abculatter2** [comment] 2017-02-02 01:45
Personally, I actually really like never having to worry about windmills in deserts. It gives you a reason to build a base there, as otherwise it's pretty much a useless biome unless you happen to have a good aesthetic idea.

**Comment by primetoxinz** [comment] 2017-02-02 01:48
Yet it removes the level of requirement for cool redstone necessity. Even though it seems trivial to all of us, people have to solve the problem of stopping gearboxes from exploding, a cool game challenge to have

**Comment by BeetoGuy** [comment] 2017-02-03 00:01
Yeah, there's an idea. Could also spend gears to fix it.

**Comment by DarianLStephens** [comment] 2017-02-09 07:02
Although that's already been implemented, I would like an option to restore gearbox exploding.
If you're feeling particularly adventurous, you could make it so that if it's repaired and broken in too quick succession, it explodes anyway.

**Comment by WolfieWaffle** [comment] 2017-02-19 20:06
This isn't directly related to the issue, but what exactly causes a gearbox to break in the first place and how do you prevent it?

**Comment by DarianLStephens** [comment] 2017-02-20 03:13
Basically? Moving too fast.
Usually caused by bad weather.

**Closed** 2017-03-03 02:37 UTC
