### ISSUE TITLE
Vanilla Chicken Breeding with Hemp Seed

### ISSUE THREAD

**Issue by Ghost8909** [BeetoGuy/BetterWithMods#580] opened 2017-09-24 23:46 UTC
Found using version BetterWithMods-1.12-2.0.10.jar

I've not reproduced this, but I managed to breed Chickens in the vanilla love-mode kissy fashion using Hemp Seed. I'd been feeding them Pumpkin Seeds and they've been acting as intended as per BWM/BTW standards. I've not tried any other seeds.

**Comment by DaedalusGame** [comment] 2017-09-25 01:00
duplicate of #576
it seems like it was already fixed, check the [buildserver](http://ci.blamejared.com/job/BetterWithMods/) build if it works there

**Closed** 2017-09-30 16:48 UTC
